changed interpolation

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -28,15 +28,16 @@ services:
   mysqldumper:
     image: mysql:8.0
     volumes:
-      - "${HOME}/Public:/backups" 
+      - "${HOME}/Public:/backups"
     entrypoint: >
-      /bin/sh -c "
+      sh -c '
+      mkdir -p /backups &&
       while true; do
         if mysqldump -h prisondb -uroot -ppassword --no-tablespaces --skip-lock-tables openmrs_prison |
-        gzip > /backups/prisonemr_dump-$(date +'%Y-%m-%d').sql.gz; then
-          find /backups -type f -name '*.sql.gz' -mtime +7 -delete
+        gzip > /backups/prison_db-$(date +%Y-%m-%d).sql.gz; then
+          find /backups -type f -name "*.sql.gz" -mtime +7 -delete
         else
-          echo 'Backup failed at $(date)' >&2
+          echo "Backup failed at $(date)" >&2
         fi
-        sleep 86400;
-      done"
+        sleep 86400
+      done'
